### ISSUE TITLE
[Feature Request] Be able to PR templates

### ISSUE THREAD

**Issue by DouglasHennrich** [SquirrelMobile/generator-titpl#2]
I'm wondering if there's a way to PR templates and how to do so.
It will be interesting to do something like `eslint` does for download an specific config. That way you guys could continue to work on your templates and the community could also create and deploy theirs =)

Thanks for your project

**Comment by SquirrelMobile** [comment]
@DouglasHennrich i've update the README to add more template into the TITPL, feel free to contribute :-) https://github.com/SquirrelMobile/generator-titpl#more-templates-
