### ISSUE TITLE
Could not find org.iotashan.titouchimageview with SDK 8.X on Android

### ISSUE THREAD

**Issue by jmcerrejon** [SquirrelMobile/generator-titpl#3]
```
[ERROR] Could not find all required Titanium Modules:
[ERROR]    id: org.iotashan.titouchimageview	 version: latest	 platform: android	 deploy-type: development
```

SDK: 8.1.1.GA
titpl: 1.3.0.
Platform: Android

**Comment by SquirrelMobile** [comment]
@jmcerrejon hi, sorry for the delay. We rebuild the module to make it works with the last version of Titanium. You can use the 1.4.0 version of titpl for a new project or get the last version here https://github.com/SquirrelMobile/generator-titpl/tree/master/app/templates/burger/modules/android/org.iotashan.TiTouchImageView/2.0.2 for an existing project.
